evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evt



my_app_mail:
    resource: "@MyAppMailBundle/Resources/config/routing.yml"

graphe:
    resource: "@GrapheBundle/Resources/config/routing.yml"
    prefix:   /

scrum:
    resource: "@ScrumBundle/Resources/config/routing.yml"
    prefix:   /Project

sprint:
    resource: "@SprintBundle/Resources/config/routing.yml"
    prefix:   /Sprint
Userstory:
    resource: "@UserstoryBundle/Resources/config/routing.yml"
    prefix:   /
team:
    resource: "@TeamBundle/Resources/config/routing.yml"

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

messaging:
    resource: "@MessagingBundle/Resources/config/routing.yml"
    prefix:   /chat
forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /
activity:
    resource: "@ActivityBundle/Resources/config/routing.yml"
    prefix:   /
tasks:
    resource: "@TasksBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /afficher_meetings